---
title: "Module 5 Assignments"
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(readxl)
assignments <- read_excel("assessment_schedule.xlsx") %>% 
  mutate(formatted_date = format(due_date, "%A, %B %d, %Y"))
```

# Short Project 04

**Due date: `r assignments %>% filter(assessment == "Short Programming Project 4") %>% pull(formatted_date)` at 9pm**

Short Programming projects are submitted during our weekly 45-minute in-person lab sessions. Each lab sessions is guided by two TAs. The instructions for the short project will be available only during the lab sessions. To schedule your lab session go to the weekly lab session spreadsheet in [Short Project Dates and Instructions](short-projects.html).

# Programming Problems

Programming Problems should be submitted to [gradescope](https://www.gradescope.com/courses/822022).

## Programming Problem 9

**Due date: `r assignments %>% filter(assessment == "Module 5 Programming Problems") %>% pull(formatted_date)`  at 9pm**

Write a Python function that does the following:

1.  Its name is `count_vowels`
2.  It takes one string as argument
3.  It counts how many vowels there are in the string using a `while` loop
4.  It returns an integer representing the number of vowels (`a`, `e` `i`, `o`, `u` -- both lowercase and uppercase) found in the argument
5.  You can (and should) use the operator `in`
6.  You are not allowed to use built-in count methods or functions

Name the program `vowels.py`. Make sure that gradescope gives you the points for passing the test cases.

Test cases for development:

```{python}
#| eval: false
#| echo: true
def main():
  print( count_vowels("") ) # 0
  print( count_vowels("aaa") ) # 3
  print( count_vowels("AEIOU") ) # 5
  print( count_vowels("cysts") ) # 0
  
main()
```


## Programming Problem 10

**Due date: `r assignments %>% filter(assessment == "Module 5 Programming Problems") %>% pull(formatted_date)` at 9pm**

Write a Python function that does the following:

1.  Its name is `reverse_string`
2.  It takes one string as argument
3.  Using a `while` loop, it builds a new string that is the reverse of the original string
4.  It returns the reversed string

Write a Python function that does the following:

1.  Its name is `remove_spaces`
2.  It takes one string as argument
3.  Using a `while` loop to create a string with no spaces
4.  Return the news string with no spaces

Write a Python function that does the following:

1.  Its name is `is_palindrome`
2.  It takes one string as argument
3.  It checks whether the string is a palindrome. A Palindrome reads the same backward and forward. For example: madam, and nurses run
4.  It returns `True` if the string is a palindrome, and `False` otherwise
5.  Use your `remove_spaces` function to remove spaces from the argument before you check if the string is a palindrome
6.  Use your `reverse_string` function to reverse the string and then compare the result to the original string

Name the program `palindrome.py`. Make sure that gradescope gives you the points for passing the test cases.

```{python}
#| eval: false
#| echo: true
def main():
  print( reverse_string("aeiou") ) # uoiea
  print( remove_spaces("ae io ua") ) # aeioua
  
  print( is_palindrome("noon") ) # True
  print( is_palindrome("deified") ) # True
  print( is_palindrome("go deliver a dare vile dog") ) # True
  
main()
```