---
title: "CSc 110 Computer Programming I"
website:
  google-analytics: "G-X5E6TNHNQ5"
  cookie-consent: true
---

# Welcome to CSc 110!

This is an introduction to programming with an emphasis on solving problems drawn from a variety of domains. Topics include basic control and data structures, problem solving strategies, and software development tools and techniques. Specifically, the Python programming language will be taught.

-   Course D2L: [d2l.arizona.edu/d2l/home/1257984](https://d2l.arizona.edu/d2l/home/1325409)

Where to start:

-   [Syllabus](syllabus.html)

-   [Schedule](schedule.html)

# Instructor Information

-   Adriana Picoral [🔈](https://namedrop.io/adrianapicoral "how to pronounce Adriana Picoral")

    -   Office: [Gould-Simpson](https://goo.gl/maps/h8Vyf7RNQiMAScDY6) 811

    -   Email: adrianaps\@arizona.edu

    -   Instructor Website: [adrianapicoral.com](https://adrianapicoral.com/)

    -   Office hours (open door, drop in, my office [GS](https://goo.gl/maps/h8Vyf7RNQiMAScDY6) 811):

        -   Tuesday 1pm to 3pm

        -   Wednesday 11:30am to 12:30pm

<br/>

-   Xinchen Yu

    -   Office: Gould-Simpson 854

    -   Email: xinchenyu\@arizona.edu

    -   Instructor Website: [xinchenyu.github.io](https://xinchenyu.github.io/)

    -   Office hours (open door, drop in, my office GS 854):

        -   Wednesday 3:00pm to 5:30pm
