---
title: "Programming Project 11"
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(readxl)
assignments <- read_excel("assessment_schedule.xlsx") %>% 
  mutate(formatted_date = format(due_date, "%A, %B %d, %Y"))
```

Programming Projects are to be submitted to [gradescope](https://www.gradescope.com/courses/934148).

**Due date: `r assignments %>% filter(assessment == "Programming Project 11") %>% pull(formatted_date)` at 9pm**

This programming project is an adaptation of Ben Dicken's WordSearch Programming Assignment.

# WordSearch

In this assignment, you will be tasked with writing a program that finds certain words within a wordsearch grid and returns the word mapped to the line and starting character location of each word. The information of the board, and the words will be provided via files you will need to read in. 

You should name the file `wordsearch.py`. Your code should have a `main` function that print a dictionary (see specification below).

## Words text file

Your program should open up and read a text file name which determines which words you are searching for in your puzzle file! You can assume that each line in the input text file is formatted as follows: each line of the file is a word from the "word bank". 

Contents of `words.txt`:

```{html}
computer
science
```


## Puzzle text file

This file contains a grid of letters and hidden within those letters are certain words you will need to be searching for. You will use the words in `words.txt` to figure out what letter combination of words you need to find. This is an example of what this word-grid file would look like:

<pre>
W O D I W S M Z H 
N R M E W A N D A 
L Z H I N O K L H 
S R E G N E V A V 
I F R C X H C Q X 
A H T Z B A Y K Q 
A R A M E R I C A
</pre>

The puzzle file could have more or less Rows/Columns depending on each test case.

## Output

The program should return a dictionary with the starting row / col locations for each word found. Your code should have a `main` function and you need to call the `main` function to print this dictionary. The formatting of the dictionary should be something like:

```{python}
#| eval: false
{"word1": [1, 1], "word2": [5, 5]}
```


# Example Run

Say that `words.txt` contains:

```{html}
army
navy
star
america
bullet
```

And then `grid.txt` contains:

<pre>
Z S Y M R A Z
R N Z Z A Q L
M A T R T U I
N V Y A S S D
B Y Z T C V B
V B U L L E T
A M E R I C A
</pre>

Your program should print:

```{python}
#| eval: false
{"army": [1, 6],
 "bullet": [6, 2],
 "america": [7, 1],
 "navy": [2, 2],
 "star": [4, 5]}
```

A word in the grid can be horizontal or vertical, the order of letters may go forward or backward. For example, when searching for the word `star`, the starting position is row 4 and column 5 for the letter `s` (vertical backward direction). Another example is the word `bullet`, the starting position is row 6 and column 2 for the letter `b` (horizontal forward direction). Consider the cases when a word only show up once in the grid.

# Additional Example 

Say that `words.txt` contains:

```{html}
house
roof
table
kitchen
computer
bedromm
bathroom
```

And then `grid.txt` contains:

<pre>
I L D T J R K I I I J N D A I D O W R S
K P G M N J Z Q C T X J Y Y Q C E K W E
I M K S I P M R V A J J T X J Z U H Y B
U E T X N E V K M B S V Z A T Z U M N M
X H Z F B J W S W U L M Q P X L Z A K V
O L B E D R O O M Z H T C V A W B R O O
H C T K F A J Q V J I Q I O J S S Q X A
N V H B P I A D U O B P O P J X Y N Y O
H B T I B A T H R O O M F A J I X O T X
Z Y U C H O U S E O V S M O W M T P F V
K B G I W T F M N I G X I A H R H N D O
H Q N W Z T N D C F V A W O N J C V T C
N T U I X Y M T A B L E F W B F J Y D M
K O X W T C Y Q I H H D R T W I E C I X
U O Q A F X J H V H L Z S U V B K A U R
T N U Z A I G Q N C Q K I T C H E N R K
N O D C I J O H N Q W R B P B Y V N S C
H P C O M P U T E R L N H H T J W X Y A
M A D J S O V L R O O F Y K D T E I M A
U Q I W X E D J O R L D R H P R C W Y O
</pre>

Your program should print:

```{python}
#| eval: false
{'house': [10, 5], 
 'roof': [19, 9], 
 'table': [13, 8], 
 'kitchen': [16, 12], 
 'computer': [18, 3], 
 'bathroom': [9, 5]}
```

# Development Strategy 1

This section covers how you should go about structuring and implementing the code. In total, your program should have at least 4 functions. My recommendation for these functions:

```{python}
#| eval: false

# All your functions are defined here

def main():
    word_filename = input("Name of the word bank file: ")
    grid_filename = input("Name of the grid file: ")
    
    # call a function to load in the forwards words, computes the backwards version of each word, and save into a dictionary, passing in the needed arguments
    
    # call a function for transposing the grid, passing in the needed arguments

    # call a function for searching through lines, passing in the needed arguments
    
    # call a function for checking if a word is found on a line and where it is (index), passing in the needed arguments
    
    # print the dictionary with words as keys and their positions as values

main()
```

You may have other functions as well and use your preferred names for them, but you MUST call your `main` function when submitting your file. Your `main` function should call `print` function only once, which is in the last step to print the dictionary. You may build this program in the following sequence:

## (1) Reading in input files

Create a function that will be responsible for opening up the words file and reading in the information. You can pass the file name into this function via arguments / parameters. The function should iterate through the lines and create a dictionary that maps the forwards-spelling to the backwards spelling. After the data is read in, the function should return the dictionary back to main. Next, open word input grid file up.

## (2) Word search

Horizontal search is a bit easier than vertical mode, so I recommend that you work on this first. Create a function for this, and pass it the word dictionary, the grid file, and the mode. Iterate through the lines of the file one-at-a-time. For each line you encounter, you can search for all of the words in the word dictionary to see if you can find it.

If you try to do all of this in one function, you will probably end up with 3 or 4 levels of nested loops, which can get rather disorganized. I recommend that you create another function, perhaps called something like search_within_line that handles processing one line of searching. The horizontal function can call this for each line that it encounters.

There will be separate test cases for horizontal and for vertical. I recommend that you get the horizontal ones to pass before moving on to vertical.

In vertical search, you have to search for the words in the columns of the grid, rather than the rows. This is a bit more complex, but still very do-able. The way you should go about this is create a loop where you iterate through the column indexes. Within this loop, create another loop that goes through every character in that column and creates a list of those characters. Then, you can treat this column as if it is a row.

# Development Strategy 2

You may also consider another strategy: 

```{python}
#| eval: false
# All your functions are defined here

def main():
    word_filename = input("Name of the word bank file: ")
    grid_filename = input("Name of the grid file: ")
    
    # call a function to load in the words and save into a list, passing in the needed arguments
    
    # call a function to get each word of the 4 directions at each position, passing in the needed arguments

    # call a function to save all the words in the 4 directions for all the indices using a dictionary, passing in the needed arguments
    
    # call a function for checking if a word is found in any one of the 4 directions (the value) and where it is (the key), passing in the needed arguments
    
    # print the dictionary with words as keys and their positions as values
    
if __name__ == '__main__':
    main()
```


The 4 directions are: horizontal forward, horizontal backward, vertical forward, and vertical backward. For example, for position `[2, 2]`, the words are: `navybm`, `ns`, `nzzaql` and `nr`.

You may have other functions as well and use your preferred names for them, but you MUST call your `main` function when submitting your file. Your `main` function should call `print` function only once, which is in the last step to print the dictionary.