---
title: "tuples (class slides)"
format: revealjs
slide-number: true
df-print: kable
---

# CSc 110 - tuples

## Variable length parameter

Sometimes you want to handle a variable number of parameters (like `print` does)

```{python}
#| eval: true
#| echo: true
print(1, 2, 3)
```

## Variable length parameter

You can add a `*` before your parameter name so that it accepts a variable number of arguments, gathering them into a tuple

```{python}
#| eval: true
#| echo: true
def concatenate(*values):
  new_string = ""
  for v in values:
    new_string += str(v) + " "
  return new_string[:-1]

def main():
  print( concatenate("The", "temperature", "is", 82, "degrees"))
  
main()
```

## Write a function

1.  Its name is `maximum`
2.  It takes a variable number of arguments: `*values`
3.  It returns the highest value in `values`

```{python}
#| eval: false
#| echo: true
assert maximum(1) == 1
assert maximum(3,1) == 3
assert maximum(2,4,6) == 6
assert maximum() == None
```

## Write a function -- solution

```{python}
#| eval: true
#| echo: true
def maximum(*values):
  result = None
  for v in values:
    if result == None or v > result:
      result = v
  return result

def main():
  assert maximum(1) == 1
  assert maximum(3,1) == 3
  assert maximum(2,4,6) == 6
  assert maximum() == None
  print("Passed all tests")
  
main()
```

## Write a function

1.  Its name is `min_max`
2.  It takes a variable number of arguments: `*values`
3.  It returns the highest and lowest values in `values`

```{python}
#| eval: false
#| echo: true
assert min_max(1) == (1, 1)
assert min_max(3,1) == (1, 3)
assert min_max(2,4,6) == (2, 6)
assert min_max() == (None, None)
```

## Quiz 05

<center>
<div class="cleanslate w24tz-current-time w24tz-large" style="display: inline-block !important; visibility: hidden !important; min-width:300px !important; min-height:145px !important;"><a href="//24timezones.com/Tucson/time" style="text-decoration: none" class="clock24" id="tz24-1695057604-c1393-eyJob3VydHlwZSI6IjEyIiwic2hvd2RhdGUiOiIwIiwic2hvd3NlY29uZHMiOiIwIiwiY29udGFpbmVyX2lkIjoiY2xvY2tfYmxvY2tfY2I2NTA4ODZjNDg0OWVlIiwidHlwZSI6ImRiIiwibGFuZyI6ImVuIn0=" title="World Time :: Tucson" target="_blank" rel="nofollow"></a>current time<div id="clock_block_cb650886c4849ee"></div></div>
<script type="text/javascript" src="//w.24timezones.com/l.js" async></script>
</center>

15 minutes to complete the quiz, two problems.

* No need for comments, no need for a `main()`, no need for test cases

Allowed built-in functions: `round()`, `input()`, `float()`, `str()`, `int()`, `len()`, `range()`, `open()`, `close()` 

## Write a function -- solution

```{python}
#| eval: true
#| echo: true
def min_max(*values):
  max = None
  min = None
  for v in values:
    if max == None or v > max:
      max = v
    if min == None or v < min:
      min = v
  return min, max

def main():
  assert min_max(1) == (1, 1)
  assert min_max(3,1) == (1, 3)
  assert min_max(2,4,6) == (2, 6)
  assert min_max() == (None, None)
  print("Passed all tests")
  
main()
```
