---
title: "intro to sets (class slides)"
format: revealjs
slide-number: true
df-print: kable
---

# CSc 110 - Intro to Sets

## Data Structures in Python

-   lists (mutable)
-   dictionaries (mutable)
-   tuples (immutable)
-   sets (mutable)

## Lists

-   store:
    -   ordered items (it keeps the original order)
    -   elements of different types
    -   repeated elements
-   use square brackets (`[]`) syntax for creating a list
-   allow indexing (integers starting at `0`) with square brackets (`[]`) as well
-   are **mutable**

## Tuples

-   store:
    -   ordered items  (it keeps the original order)
    -   elements of different types
    -   repeated elements
-   use parentheses (`()`) syntax for creating a tuple
-   allow indexing (integers starting at `0`) with square brackets (`[]`)
-   are **immutable**

## Dictionaries

-   store pairs of items `key: value`
-   keys have to be unique (no repeated keys allowed)
-   use curly brackets (`{}`) with key and value separated by colon (`:`)
-   allow value retrieval through key with square brackets (`[]`)
-   are **mutable**

## Sets

-   A **set** is (another) data structure

-   Helpful ways of thinking about it

    -   A dictionary without the values

    -   A "bag" of elements

## Sets

-   Do not store items in the order you created them

-   Do not allow repeated items to be stored

-   **Cannot** use square brackets to retrieve an item

-   Use `set()` to initiate an empty set

-   Use `len()` to get number of items

-   Use `for x in set` to iterate over the elements in a set



## Set methods

* `.add(value)` adds an element to the set
* `.discard(value)` discards the specified value

You can also use the operator `in` and the function `len()` with sets 

Use the function `set()` to convert a list to a set, and `list()` to convert a set into a list

## Evaluate the code

```{python}
#| eval: false
#| echo: true
numbers = {5, 7, 10, 5, 3, 5, 9, 8, 20, 5}
numbers  # evaluate what this set holds at this point

numbers.add(30)
numbers  # evaluate what this set holds at this point

numbers.discard(10)
numbers  # evaluate what this set holds at this point
```


## Evaluate the code

```{python}
#| eval: true
#| echo: true
numbers = {5, 7, 10, 5, 3, 5, 9, 8, 20, 5}
numbers
```

```{python}
#| eval: true
#| echo: true
numbers.add(30)
numbers
```


```{python}
#| eval: true
#| echo: true
numbers.discard(10)
numbers
```

## Evaluate the code

```{python}
#| eval: false
#| echo: true
numbers_list = [2, 1, 2, 1, 3, 4, 1]
numbers_list # evaluate this line

numbers_set = set(numbers_list)
numbers_set # evaluate this line

numbers_set.add(1)
numbers_set.add(2)
numbers_set # evaluate this line

numbers_set.add(5)
numbers_set # evaluate this line

numbers_set.discard(6)
numbers_set.discard(1)
numbers_set # evaluate this line
```

## Evaluate the code

```{python}
#| eval: true
#| echo: true
numbers_list = [2, 1, 2, 1, 3, 4, 1]
numbers_list # evaluate this line
```


```{python}
#| eval: true
#| echo: true
numbers_set = set(numbers_list)
numbers_set # evaluate this line
```


```{python}
#| eval: true
#| echo: true
numbers_set.add(1)
numbers_set.add(2)
numbers_set # evaluate this line
```


```{python}
#| eval: true
#| echo: true
numbers_set.add(5)
numbers_set # evaluate this line
```


```{python}
#| eval: true
#| echo: true
numbers_set.discard(6)
numbers_set.discard(1)
numbers_set # evaluate this line
```

## Quiz 10

<center>
<div class="cleanslate w24tz-current-time w24tz-large" style="display: inline-block !important; visibility: hidden !important; min-width:300px !important; min-height:145px !important;"><a href="//24timezones.com/Tucson/time" style="text-decoration: none" class="clock24" id="tz24-1695057604-c1393-eyJob3VydHlwZSI6IjEyIiwic2hvd2RhdGUiOiIwIiwic2hvd3NlY29uZHMiOiIwIiwiY29udGFpbmVyX2lkIjoiY2xvY2tfYmxvY2tfY2I2NTA4ODZjNDg0OWVlIiwidHlwZSI6ImRiIiwibGFuZyI6ImVuIn0=" title="World Time :: Tucson" target="_blank" rel="nofollow"></a>current time<div id="clock_block_cb650886c4849ee"></div></div>
<script type="text/javascript" src="//w.24timezones.com/l.js" async></script>
</center>

You have 10 minutes to complete the quiz.

## Write a function

1.  Its name is `count_names`
2.  It opens in read mode [a file that contains a name per line](data/names.txt), with repeated names
3.  It counts how many unique names there are in the file
4.  It returns an **integer** with the count
5.  Use a **set** for this

```{python}
#| eval: false
#| echo: true
assert count_names("names.txt") == 11
```

## Write a function -- solution

```{python}
#| eval: false
#| echo: true
def count_names(file_name):
  f = open(file_name, "r")
  name_set = set()
  for line in f:
    name_set.add(line.strip())
  f.close()
  return len(name_set)

def main():
  assert count_names("names.txt") == 11
  
main()
```



## Write a function

1. Its name is `has_duplicates`
1. It takes a variable number of arguments: `*values`
1. It returns `True` if there are repeated elements in `values`, `False` otherwise

```{python}
#| eval: false
#| echo: true
assert has_duplicates(3, 2, 1, 2, 3) == True
assert has_duplicates(3, 20, 1, 2, 13) == False
```

## Write a function -- solution

```{python}
#| eval: true
#| echo: true
def has_duplicates(*values):
  unique_values = set()
  for v in values:
    if v not in unique_values:
      unique_values.add(v)
    else:
      return True
  return False

def main():
  assert has_duplicates(3, 2, 1, 2, 3) == True
  assert has_duplicates(3, 20, 1, 2, 13) == False
  
main()
```

## Write a function -- solution 2

```{python}
#| eval: true
#| echo: true
def has_duplicates(*values):
  values_set = set(values)
  return len(values) > len(values_set)

def main():
  assert has_duplicates(3, 2, 1, 2, 3) == True
  assert has_duplicates(3, 20, 1, 2, 13) == False
  
main()
```

