---
title: "Python Basics (class slides)"
format: revealjs
slide-number: true
---

# CSc 110 Python Basics

## Announcements

-   Trouble accessing Gradescope? Use the link on D2L
-   D2L grades are going to be used to calculate your final grade
-   Full schedule for office hours can be found at [xinchenyu.github.io/csc110-fall2024/tas.html](https://xinchenyu.github.io/csc110-fall2024/tas.html)

## Did you set up your workspace?

-   Did you download Python 3?
-   Did you download VS Code (or PyCharm, or Mu)?
-   If not, that's fine, you can use [vscode.dev](https://vscode.dev/)

# What is a program?

## The `print` function

-   What does the print function do?

## The `print` function

-   `print()` sends characters (strings) to the **standard output**
-   By default, the **standard output** of a python program goes to the console.

```{python}
#| echo: true
print("some characters")
```

<br />

```{python}
#| echo: true
print('some characters')
```

## String operations

String concatenation:

-   What will the standard output display when the code below is run?

```{python}
#| echo: true
#| eval: false
print("hello" + "world")
```

## String operations

In your groups, try the following operations:

-   String repetition: `"abc" * 4`
-   String concatenation with `+` and `,`. What is the difference?
-   Combine both repetition and concatenation to print the following:

```{python}
#| echo: false
#| eval: true
print("They sang", "Aa" * 10)
```

## Multiple `print` statements

-   What will the standard output display when the code below is run?

```{python}
#| echo: true
#| eval: false
print('Are')
print('You')
print('In')
print('College?')
```

## Multiple `print` statements

-   By default, the `print` function sends the output cursor to the next line after printing

```{python}
#| echo: true
#| eval: true
print('Are', end = ' ')
print('You', end = ' ')
print('In', end = ' ')
print('College?', end = ' ')
```

What other characters can you use for values for the `end` parameter?

## Dealing with special characters

Write a simple program that prints the following output to the python console:

<br />

```{=html}
<pre style="font-size: 30px">

   He said, "What's up?" 
   Joe's friend didn't reply.

</pre>
```


# Variables

## Variables and assignment

-   Variables are names in a program that represent a stored value
-   We can assign names to particular values in our program
-   When we give a value a name, or update the value stored in a variable, this is called assigning a variable

## Demonstration of variable assignment

Variable assignment does not produce any output to the console. Run the following code:

```{python}
#| echo: true
#| eval: false
first_name = "Mary"
family_name = "Silva"
```

How would we print these variables?

## Statements (vs expressions)

-   *Expressions* represent values or the computation of values
-   *Statements* represent executable steps in a program.
-   Statements often include expressions

Here's a **statement** that invokes the `print` function with the **expression** `3 + 4` as an argument.

```{python}
#| echo: true
#| eval: false
print(3 + 4)
```

## Basic Types

-   string: `"hello"` or `'hello'`
-   integer: `3`
-   float: `3.14`
-   bool: `True` or `False`

Use the function `type()` with each literal type.

## Operations

Try the following operators with the different types in python:

<br />

```{=html}
<pre style="font-size: 30px">

   +
   -
   *
   /
   //
   %
   **

</pre>
```

## Quiz 01

<center>
<div class="cleanslate w24tz-current-time w24tz-large" style="display: inline-block !important; visibility: hidden !important; min-width:300px !important; min-height:145px !important;"><a href="//24timezones.com/Tucson/time" style="text-decoration: none" class="clock24" id="tz24-1695057604-c1393-eyJob3VydHlwZSI6IjEyIiwic2hvd2RhdGUiOiIwIiwic2hvd3NlY29uZHMiOiIwIiwiY29udGFpbmVyX2lkIjoiY2xvY2tfYmxvY2tfY2I2NTA4ODZjNDg0OWVlIiwidHlwZSI6ImRiIiwibGFuZyI6ImVuIn0=" title="World Time :: Tucson" target="_blank" rel="nofollow"></a>current time<div id="clock_block_cb650886c4849ee"></div></div>
<script type="text/javascript" src="//w.24timezones.com/l.js" async></script>
</center>

You have 10 minutes to complete the quiz


## Operations and Variable Assignments

Variable assignments are not like math --- they can appear in equations that make no mathematical sense.

<br />

```{python}
#| echo: true
#| eval: false
x = 5
print(x)
x = x + 2
print(x)
```

<br />

`x = x + 2` means "take the current value of x, add it with 2, and assign the resulting value (7) to x as its new value."

## Comments

Computer program can include comments, which are simply text that is meant to be read, but not executed.

<br />

```{python}
#| echo: true
#| eval: false
# assign a radius value
radius = 3
# compute the area of a circle
area = 3.1415 * radius ** 2
```

<br />

The purpose of comments is to "document" the program so that subsequent readers can more easily understand it, or learn things about it (e.g., its original author).
