---
title: "loops + strings (class slides)"
format: revealjs
slide-number: true
---

# CSc 110 - looping through strings
  
# String Manipulation

## String indexing

-   Strings are sequences in Python
-   We can retrieve values in a sequence using `[ ]`

```{python}
#| echo: true
#| eval: true
name = "Xinchen"
name[0]
```

Note that the first index in a sequence is always `zero`.

## String indexing

Since the first index of a sequence is `zero`, the last index is going to be the length of the string `minus 1`

```{python}
#| echo: true
#| eval: true
name = "Xinchen"
len(name)
```

```{python}
#| echo: true
#| eval: true
name = "Xinchen"
name[6]
```

```{python}
#| echo: true
#| eval: false
name = "Xinchen"
name[7] # this will throw an error
```

## Evaluate expressions

```{python}
#| echo: true
#| eval: false
my_str = "Clint Eastwood"
my_str[11] + my_str[1] + my_str[13]

my_str = "cider"
my_str[0] + my_str[4] + my_str[1] + my_str[3] + my_str[2]

my_str = "dusty"
my_str[2] + my_str[3] + my_str[1] + my_str[0] + my_str[4]
```

## Evaluate expressions

```{python}
#| echo: true
#| eval: true
my_str = "Clint Eastwood"
my_str[11] + my_str[1] + my_str[13]
```

```{python}
#| echo: true
#| eval: true
my_str = "cider"
my_str[0] + my_str[4] + my_str[1] + my_str[3] + my_str[2]
```

```{python}
#| echo: true
#| eval: true
my_str = "dusty"
my_str[2] + my_str[3] + my_str[1] + my_str[0] + my_str[4]
```

## Write a function

Function `four_letter_anagram` takes a `string`, and four integers `a`, `b`, `c` and `d`.
It returns the anagram of the string according to the indices `a`, `b`, `c` and `d` -- concatenate the individual characters.

Name your file `anagram.py` and submit it for attendance.

Test cases:
```{python}
#| eval: false
#| echo: true
assert four_letter_anagram("balm", 2, 1, 3, 0) == 'lamb'
assert four_letter_anagram("loin", 0, 2, 1, 3) == 'lion'
assert four_letter_anagram("reap", 3, 1, 2, 0) == 'pear'
```


## Write a function - solution 

```{python}
#| echo: true
#| eval: true
def four_letter_anagram(word, a, b, c, d):
  return word[a] + word[b] + word[c] + word[d]

def main():
  assert four_letter_anagram("balm", 2, 1, 3, 0) == 'lamb'
  assert four_letter_anagram("loin", 0, 2, 1, 3) == 'lion'
  assert four_letter_anagram("reap", 3, 1, 2, 0) == 'pear'

main()
```


## `in` operator

The `in` operator determines whether a given value is a constituent element of a sequence (such as a string)

```{python}
#| eval: true
#| echo: true
"i" in "Xinchen"
```

```{python}
#| eval: true
#| echo: true
"inc" in "Xinchen"
```

```{python}
#| eval: true
#| echo: true
"i" in "aeiou"
```

## Evaluate the expressions

```{python}
#| eval: false
#| echo: true
"a" in "aeiou"
"b" in "aeiou"
not "b" in "aeiou"
"0" in "0987654321."
"10.0" in  "0987654321."
```

## Evaluate the expressions

```{python}
#| eval: true
#| echo: true
"a" in "aeiou"
```


```{python}
#| eval: true
#| echo: true
"b" in "aeiou"
```


```{python}
#| eval: true
#| echo: true
not "b" in "aeiou"
```


```{python}
#| eval: true
#| echo: true
"0" in "0987654321."
```


```{python}
#| eval: true
#| echo: true
"10.0" in  "0987654321."
```

## Before we proceed, a refresher ...

Remember the string method`.isnumeric()`?

```{python}
#| eval: true
#| echo: true
user_input = "paul"
user_input.isnumeric()
```

```{python}
#| eval: true
#| echo: true
user_input = "12"
user_input.isnumeric()
```

```{python}
#| eval: true
#| echo: true
user_input = "12.5"
user_input.isnumeric()
```


## Write a function

Write a function `is_numeric_one_char` that takes one `string` argument of any length (assume length > 0).

It returns `True` if the **first character** of the argument is a digit (0-9), `False` otherwise (use `[ ]` to index the string and the `in` operator).

Test cases:

```{python}
#| eval: false
#| echo: true
  assert is_numeric_one_char("0") == True
  assert is_numeric_one_char("000")  == True
  assert is_numeric_one_char("9") == True
  assert is_numeric_one_char("a") == False
```

## Write a function -- solution

```{python}
#| echo: true
#| eval: true
def is_numeric_one_char(string):
  return string[0] in "0123456789"

def main():
  assert is_numeric_one_char("0") == True
  assert is_numeric_one_char("000")  == True
  assert is_numeric_one_char("9") == True
  assert is_numeric_one_char("a") == False
  
main()
```

## Improving on `is_numeric_one_char()`

How to check every character in a string of any length?

For example, how to check if every character in `"BladeRunner2049"` is a digit (0-9)?


## While loops -- using an index

-   One technique that can be used to control the number of loop iterations is using an index variable
-   For while loops, an index variable is:
    -   Defined before the loop
    -   Used in the condition of the loop
    -   Incremented within the loop

## While loops -- using an index

Print characters at even indices.
```{python}
#| eval: true
#| echo: true
word = "BladeRunner2049"
index = 0
while index < len(word):
    print(word[index])
    # Can add other lines here too
    index = index + 2
```


## Improve on `is_numeric_one_char()`

Function name `is_numeric` that takes one `string` argument of any length (assume length > 0).

It returns `True` if every character in the argument is a digit (0-9), `False` otherwise.
Use a while loop with a  `len()` condition, update the index in the while loop.

```{python}
#| echo: true
#| eval: false
assert is_numeric("0") == True
assert is_numeric("1090") == True
assert is_numeric("95") ==  True
assert is_numeric("10a") == False
```

## `is_numeric()` solution

```{python}
#| eval: true
#| echo: true
def is_numeric(my_string):
  index = 0
  while index < len(my_string):
    if my_string[index] not in "0123456789":
      return False
    index += 1
  return True

def main():
  assert is_numeric("234") == True
  assert is_numeric("abc") == False
  assert is_numeric("12c") == False
  assert is_numeric("12.3") == False
  
main()
```

## Quiz 05

<center>
<div class="cleanslate w24tz-current-time w24tz-large" style="display: inline-block !important; visibility: hidden !important; min-width:300px !important; min-height:145px !important;"><a href="//24timezones.com/Tucson/time" style="text-decoration: none" class="clock24" id="tz24-1695057604-c1393-eyJob3VydHlwZSI6IjEyIiwic2hvd2RhdGUiOiIwIiwic2hvd3NlY29uZHMiOiIwIiwiY29udGFpbmVyX2lkIjoiY2xvY2tfYmxvY2tfY2I2NTA4ODZjNDg0OWVlIiwidHlwZSI6ImRiIiwibGFuZyI6ImVuIn0=" title="World Time :: Tucson" target="_blank" rel="nofollow"></a>current time<div id="clock_block_cb650886c4849ee"></div></div>
<script type="text/javascript" src="//w.24timezones.com/l.js" async></script>
</center>

You have 10 minutes to complete the quiz.

No need to write `main()` function.

## `is_numeric()` solution

How do we change our function so that the last test case ("12.3") returns `True` instead?

```{python}
#| eval: true
#| echo: true
def is_numeric(my_string):
  index = 0
  while index < len(my_string):
    if my_string[index] not in "0123456789":
      return False
    index += 1
  return True

def main():
  assert is_numeric("234") == True
  assert is_numeric("abc") == False
  assert is_numeric("12c") == False
  assert is_numeric("12.3") == False # how to return True?
  
main()
```

## `is_numeric()` solution

How do we change our function so that the last test case ("1.2.3") returns `False` instead?

```{python}
#| eval: true
#| echo: true
def is_numeric(my_string):
  index = 0
  while index < len(my_string):
    if my_string[index] not in "0123456789.":
      return False
    index += 1
  return True

def main():
  assert is_numeric("234") == True
  assert is_numeric("abc") == False
  assert is_numeric("12c") == False
  assert is_numeric("12.3") == True
  assert is_numeric("1.2.3") == True # how to return False?
  
main()
```

## `is_numeric()` -- solution 1

```{python}
#| eval: true
#| echo: true
def is_numeric(my_string):
  index = 0
  count_period = 0
  while index < len(my_string):
    if my_string[index] == ".":
      count_period += 1
    if my_string[index] not in "0123456789." or count_period > 1:
      return False
    index += 1
  return True

def main():
  assert is_numeric("234") == True
  assert is_numeric("abc") == False
  assert is_numeric("12c") ==  False
  assert is_numeric("12.3") == True
  assert is_numeric("1.2.3") == False
  
main()
```

## `is_numeric()` -- solution 2

```{python}
#| eval: true
#| echo: true
def is_numeric(my_string):
  # create control variable for one decimal point
  decimal_point = False
  # create index variable
  index = 0
  while index < len(my_string):
    # first check, can character be found in a number?
    if my_string[index] not in "0123456789.":
      return False
    # second check, if a period, has a period been found before?
    if my_string[index] == ".":
      if decimal_point: # a previous period was detected
        return False
      else: # first period detected
        decimal_point = True
    # increment index  
    index += 1
  # while loop executed without returning False
  # that means every character is valid, so return True
  return True

def main():
  assert is_numeric("234") == True
  assert is_numeric("abc") == False
  assert is_numeric("12c") ==  False
  assert is_numeric("12.3") == True
  assert is_numeric("1.2.3") == False
  
main()
```