---
title: "Online discussion and office hours"
---

READ THE INFORMATION BELOW, IT'S **VERY** IMPORTANT.

# Q & A: Piazza

-   Off-class discussions among students and questions to the instructors/TAs will be conducted via Piazza. 

    -   [Piazza link](https://piazza.com/arizona/spring2025/csc110)
    -   Access code: wildcats

-   Do **not** direct message (DM) TAs.

-   Do **not** share code solutions. You are free to share error messages, but not code. TAs and instructors can access your submission on gradescope.

-   It is expected that everyone will participate in the online discussion in a mature and respectful manner. Do not demean or embarrass others. Do not make sexist, racist, xenophobic, homophobic, transphobic, or victim-blaming comments. Immature, aggressive, or disrespectful behavior will not be tolerated. If you see anyone breaking this rule, report that person to me (xinchenyu\@arizona.edu)

# Online office hours

-   Online office hours with the instructor or the TAs will be a) announced over Piazza and b) conducted remotely over Zoom. Please check D2L for the zoom links.



